steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-east1-docker.pkg.dev/csci-5410-439301/serverless-frontend/qdp:latest'
    - '-f'
    - './frontend/Dockerfile'
    - './frontend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/csci-5410-439301/serverless-frontend/qdp:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'serverless-sdp7-gitlab'
  - '--image'
  - 'us-east1-docker.pkg.dev/csci-5410-439301/serverless-frontend/qdp:latest'
  - '--region'
  - 'us-east1'
  - '--platform=managed'
  - '--min-instances=1'
  - '--allow-unauthenticated'
  - '--port=3000'
  
images:
- 'us-east1-docker.pkg.dev/csci-5410-439301/serverless-frontend/qdp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
